### PR TITLE
Add a container-based collection script

### PR DESCRIPTION
**Pull request by ekohl**
This script allows easy collection of various os-release files. For Fedora this output slightly differs.

### CODE REVIEW

**Comment by stejskalleos** [comment]
Thanks @ekohl,
just two nits:
* can you please remove the empty file https://github.com/stejskalleos/os_release/blob/240158d7c642f3e7c39c85a69b0db8460a13d3cf/centos/8.4.txt? 
* Seeing different file for container versions of Fedora, maybe it would be worthy to have two versions of `os_release` files for fedora - one for container version and one for classic, what do you think?

otherwise LGTM

**Comment by ekohl** [comment]
> can you please remove the empty file https://github.com/stejskalleos/os_release/blob/240158d7c642f3e7c39c85a69b0db8460a13d3cf/centos/8.4.txt?

Oh, I missed this. It's a side effect of when the script fails: it still outputs the file. Will fix



> Seeing different file for container versions of Fedora, maybe it would be worthy to have two versions of `os_release` files for fedora - one for container version and one for classic, what do you think?

I also noticed this. Do you want to make them `VERSION-container.txt`?

Another thing: they are valid shell files so should we use the `.sh` extension for syntax highlighting?

**Comment by stejskalleos** [comment]
> I also noticed this. Do you want to make them VERSION-container.txt?

Yes, that would be great.

> Another thing: they are valid shell files so should we use the .sh extension for syntax highlighting?

Make sense, I'll update the files already created in main branch.

**Comment by ekohl** [comment]
Updated per our discussion.

**Comment by stejskalleos** [comment]
Thanks @ekohl !

**Pull request merged**
